#!/command/with-contenv bash

cd /home/jovyan/project

exec s6-setuidgid jovyan jupyter lab \
  --ip=0.0.0.0 \
  --port=8889 \
  --no-browser \
  --ServerApp.token='' \
  --ServerApp.password='' \
  --ServerApp.allow_origin='*' \
  --ServerApp.base_url="${NB_PREFIX}" \
  --ServerApp.allow_remote_access=True
