apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: kubeflow-notebook-uv
  namespace: kubeflow-user
  labels:
    app: kubeflow-notebook-uv
spec:
  template:
    spec:
      serviceAccountName: default-editor
      containers:
      - name: notebook
        image: danieldu28121999/kubeflow-notebook-uv:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan
        env:
        - name: NB_PREFIX
          value: /notebook/kubeflow-user/kubeflow-notebook-uv
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-kubeflow-notebook-uv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-kubeflow-notebook-uv
  namespace: kubeflow-user
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
